// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnRotOuBhYc1QhcPvmnLCxJZMXu_TiWKQ',
    appId: '1:267681321898:web:6318e6e12154dac12991d3',
    messagingSenderId: '267681321898',
    projectId: 'skin-care-4ae04',
    authDomain: 'skin-care-4ae04.firebaseapp.com',
    storageBucket: 'skin-care-4ae04.firebasestorage.app',
    measurementId: 'G-M7MQB262P2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB26WMShKNniUNzDK3rhuB3mWw7LQ4AXrY',
    appId: '1:267681321898:android:8e99d504f2fa8d2f2991d3',
    messagingSenderId: '267681321898',
    projectId: 'skin-care-4ae04',
    storageBucket: 'skin-care-4ae04.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGAsSKAec3OU18UxUu6YzN45KMWKIBVmo',
    appId: '1:267681321898:ios:527c51bee7716a822991d3',
    messagingSenderId: '267681321898',
    projectId: 'skin-care-4ae04',
    storageBucket: 'skin-care-4ae04.firebasestorage.app',
    iosBundleId: 'com.skincare.skinCareApp',
  );

}