name: Build & Deploy

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  web-deploy:
    name: Web Build & Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      # Исправляет ошибку "No file found for asset: .env"
      - name: Create dummy .env file
        run: touch .env

      - name: Build web
        run: flutter build web --release --base-href /lume/ --no-wasm-dry-run

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web

  android-build:
    name: Android APK Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      # Исправляет ошибку "No file found for asset: .env"
      - name: Create dummy .env file
        run: touch .env

      - name: Extract SHA-1
        run: keytool -list -v -keystore ~/.android/debug.keystore -alias androiddebugkey -storepass android -keypass android

      - name: Build release APK
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk